### ISSUE TITLE
Desktop cube trails off to right side of screen along with other distortions

### ISSUE THREAD

**Issue by Christmaswreath** [Schneegans/Desktop-Cube#150] opened 2023-12-24 03:37 UTC
#### Sorry for the drive link the video is too big to be uploaded directly
https://drive.google.com/file/d/1NB3iaLTqZO_MKDVLL1UitZrv9pZRQKTx/view?usp=drive_link

## System
_Please complete the following information:_
 - Linux distribution [Arch Linux]
 - Desktop Cube version [20]
 - GNOME Shell version: [45]

**Comment by Schneegans** [comment] 2023-12-24 08:07
This looks like you have a secondary monitor on the right? If so, this issue is explained in this video: https://www.youtube.com/watch?v=dpYyn1BXGjU

**Comment by Christmaswreath** [comment] 2023-12-24 13:08
I have an oculus rift connected to my pc, which uses an hdmi cable, but even before this happened it was plugged in...

**Comment by Schneegans** [comment] 2023-12-26 19:07
Well, I am still pretty sure that this is related to a secondary output. Can you please make sure that no secondary output is visible in you display configuration?

Also, have to tested the setting for fixing the cube's perspective as shown in the video I linked? And have you tried both X11 and Wayland?

**Comment by Schneegans** [comment] 2024-02-18 18:33
Do you have any feedback on this one? If not, I'll close this as I cannot reproduce the issue.

**Comment by Christmaswreath** [comment] 2024-02-18 18:35
I think I was using X11 because I couldn't get Wayland working. That's it.

**Comment by Schneegans** [comment] 2024-02-18 18:48
So it's working now for you?

**Comment by Christmaswreath** [comment] 2024-02-18 18:50
Switched to Mac. Bug is still there on multiple distros I tried before the Mac, though.

[Loxton Walztoni](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=2h1q0j)	[2h1q0j]
Thanks,
~Loxton

On February 18, 2024 at 18:48 GMT, Simon Schneegans ***@***.***> wrote:

So it's working now for you?

**Comment by Christmaswreath** [comment] 2024-02-18 18:50
Switched to Mac. Bug is still there on multiple distros I tried before the Mac, though.

**Comment by Schneegans** [comment] 2024-02-18 18:55
So do you still have a PC which exhibits this issue and you want help fixing it or not? I am pretty sure that this is a configuration issue on your end and not a bug in the Desktop Cube. If you do not experience the issue ATM, we can close this issue.

**Comment by Schneegans** [comment] 2024-02-18 19:35
Well, that's weird. Then it must be somewhat hardware-related. For some reason, GNOME Shell assumes that your logical screen area is larger than your display area. As if a secondary screen was attached.

I'll close this issue for now, but if you happen to install a distro with GNOME again, feel free to re-open this issue and maybe we can debug this then!

**Closed by Schneegans** 2024-02-18 19:35 UTC
Labels: bug
