### ISSUE TITLE
Issue within Pop OS around Showing Workspaces when Extension is being Used

### ISSUE THREAD

**Issue by Lito-Frito** [Schneegans/Desktop-Cube#157] opened 2024-03-03 17:44 UTC
## Describe the Bug
In PopOS, there's a "Show Workspace" button/feature. There are several ways to trigger this view (e.g. the button or "hot corners"). When this extension is installed, if you click this button or use the hot corner, everything except the desktop disappears and all windows become unusable. I have to log out/back in so that everything goes back to normal.

1. Use Pop OS
2. Install extension
3. Click Show Workspaces or use Hot Corner shortcut
5. Log out and back in for error to go away

You may also check the output of GNOME Shell for any error messages.
This can be done with the following terminal command:

```

## Expected Behavior
I should be able to see my Workspaces either through the button or hot corner while NOT losing functionality of windows.

## System
_Please complete the following information:_
 - Linux distribution [Pop!_OS 22.04 LTS x86_64
 - Desktop Cube version [23]
 - GNOME Shell version: [gnome-terminal/bash 5.1.16]
 
 PS: I love this extension. Have been using it since Mint with very little issues. I love Pop more than Mint, so I really hope I can continue to use this. Regardless, appreciate all the effort in maintaining and helping others. You are so real

**Comment by Schneegans** [comment] 2024-03-15 05:01
Hi there! Sorry for the late reply. I think that this is pretty much a duplicate of #71. I haven't used Pop OS, but maybe you could disable the "Cosmic Workspaces" extension in order to get working system which is mostly Pop OS but also has a cube?

**Closed by Schneegans** 2024-03-15 05:01 UTC
Labels: bug

**Comment by Lito-Frito** [comment] 2024-03-15 16:51
No worries! And thank you for even taking the time to respond!

Apologies for the dupe, I missed that issue. I'll try out what you said and see if it works.

Thank you!
