### ISSUE TITLE
Graphical artifacts when used together with blur-my-shell extension

### ISSUE THREAD

**Issue by RushingAlien** [Schneegans/Desktop-Cube#158] opened 2024-03-04 20:57 UTC
## Describe the Bug
It seems that there are graphical artifacts/glitches when desktop-cube is used together with blur-my-shell

1. Install both blur-my-shell and desktop cube
2. Enable both
3. Mess around in overview
4. See artifacts

You may also check the output of GNOME Shell for any error messages.
This can be done with the following terminal command:

journalctl -f -o cat | grep -E 'desktop-cube|'
```
g_signal_handler_disconnect: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
invalid (NULL) pointer instance
g_signal_handler_disconnect: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
invalid (NULL) pointer instance
g_signal_handler_disconnect: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
invalid (NULL) pointer instance
g_signal_handler_disconnect: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
invalid (NULL) pointer instance
g_signal_handler_disconnect: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
invalid (NULL) pointer instance
g_signal_handler_disconnect: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
invalid (NULL) pointer instance
g_signal_handler_disconnect: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
invalid (NULL) pointer instance
g_signal_handler_disconnect: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
invalid (NULL) pointer instance
g_signal_handler_disconnect: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
invalid (NULL) pointer instance
g_signal_handler_disconnect: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
invalid (NULL) pointer instance
g_signal_handler_disconnect: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
invalid (NULL) pointer instance
g_signal_handler_disconnect: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
invalid (NULL) pointer instance
g_signal_handler_disconnect: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
invalid (NULL) pointer instance
g_signal_handler_disconnect: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
invalid (NULL) pointer instance
g_signal_handler_disconnect: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
invalid (NULL) pointer instance
g_signal_handler_disconnect: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
invalid (NULL) pointer instance
g_signal_handler_disconnect: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
invalid (NULL) pointer instance
g_signal_handler_disconnect: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
invalid (NULL) pointer instance
g_signal_handler_disconnect: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
invalid (NULL) pointer instance
```
## Expected Behavior
No artifacts

## System
_Please complete the following information:_
# Laporan Rincian Sistem
---

## Rincian laporan
- **Tanggal dihasilkan:**                          2024-03-05 03:56:42

## Hardware Information:
- **Model Perangkat Keras:**                       ADVAN 1701
- **Memori:**                                      16,0 GiB
- **Prosesor:**                                    AMD Ryzen™ 7 7735HS with Radeon™ Graphics × 16
- **Grafik:**                                      AMD Radeon™ Graphics
- **Kapasitas Diska:**                             1,0 TB

## Software Information:
- **Versi Firmware:**                              6.02
- **Nama OS:**                                     Arch Linux
- **Build OS:**                                    rolling
- **Tipe OS:**                                     64-bit
- **Versi GNOME:**                                 45.4
- **Sistem Jendela:**                              Wayland
- **Versi Kernel:**                                Linux 6.7.7-1-cachyos

**Comment by RushingAlien** [comment] 2024-03-04 20:58
Video is to big so I'll upload it elsewhere and link it here

**Comment by Schneegans** [comment] 2024-03-15 04:51
Hi there! Will you upload the video? Btw, have you checked #3? This could be related.

**Comment by Schneegans** [comment] 2024-04-04 06:38
Any updates on this one? Else I'll close it as I cannot reproduce your issues.

**Closed** 2024-04-09 19:23 UTC
Labels: bug
