### ISSUE TITLE
Desktop Swipe Gestures stop working after screen lock on GNOME 46

### ISSUE THREAD

**Issue by Neo-29** [Schneegans/Desktop-Cube#164] opened 2024-03-29 19:51 UTC
## Describe the Bug

1. Lock
2. Come back (unlock)

You may also check the output of GNOME Shell for any error messages.
This can be done with the following terminal command:

journalctl -f -o cat | grep -E 'desktop-cube|'
```
Error connecting to Touchégg daemon: Could not connect: Connection refused
Reconnecting in 5 seconds...

(tracker-extract-3:9608): GLib-GIO-WARNING **: 20:48:19.502: Error creating IO channel for /proc/self/mountinfo: Argument invalide (g-io-error-quark, 13) 
```

## Expected Behavior
gestures should work as expected with pad

## System
_Please complete the following information:_
 - Linux distribution [arch linux
 - Desktop Cube version last one
 - GNOME Shell version: 46 on wayland

**Comment by Schneegans** [comment] 2024-04-01 18:34
Hi there! Thanks for the report. What exactly do you mean with "stop working"?

Btw, this could be related to #162.

**Comment by Neo-29** [comment] 2024-04-03 21:45
Coming back from lock, it breaks the swipe to switck desktop with the pad.
All other gestures work

Same problem with `unite` extension

**Comment by Schneegans** [comment] 2024-04-04 06:28
After reading your [GNOME Shell bug report](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/7538) I keep wondering _how exactly_ do you test which extension could cause the issue? As mentioned by Sebastian in the other issue, GNOME Shell extensions do modify GNOME Shell's source code. If they are buggy, this can result in all kind of weird things. **Especially, it can mean that side effects remain even after disabling an extension.**

This means, to test this properly, you will have to do the following:
* Disable all extensions.
* Restart your session: Either logout / login or reboot your system.
* Enable _one_ extension and check for issues.
* Disable it again, restart again, check the next one.

Have you done it this way?

**Comment by Neo-29** [comment] 2024-04-04 10:29
I already did that... Again an again.
I get rid of the extension
Everything works fine.
What else do you want me to say?

**Comment by Schneegans** [comment] 2024-04-09 19:12
I just installed the latest Fedora 40 with vanilla GNOME 46 and screen locking works just fine.

I see you have Touchégg installed. Could this cause some issues?

**Comment by Neo-29** [comment] 2024-04-09 19:23
> I just installed the latest Fedora 40 with vanilla GNOME 46 and screen locking works just fine.
> 
> I see you have Touchégg installed. Could this cause some issues?

With or without the issue remains.

The pb is the extension can work a moment, in particular if no other ones are installed...


The issue is not desktop cube specific

Butt for sure there's something in the settings causing that.

**Comment by ssamsel** [comment] 2024-04-11 18:33
I am having the same issue on Arch Linux when resuming from suspend. I created a hack fix by putting this script in `/usr/lib/systemd/system-sleep/cube_fix.sh`:
````
#!/bin/sh
if [ "${1}" == "pre" ]; then
  gnome-extensions disable desktop-cube@schneegans.github.com
elif [ "${1}" == "post" ]; then
  gnome-extensions enable desktop-cube@schneegans.github.com
fi
````

**Comment by Sidethorn** [comment] 2024-04-12 09:01
I don't know if it's related to this but  drag windows to adjacent workspaces is not working anymore

**Comment by Schneegans** [comment] 2024-04-12 11:34
@Sidethorn I guess that this is not related. Could you open a new issue?

**Comment by Neo-29** [comment] 2024-04-12 12:51
> I don't know if it's related to this but drag windows to adjacent workspaces is not working anymore

Confirmed

Like that for a while

**Comment by FelixFourcolor** [comment] 2024-05-25 20:24
I have the same problem, and I don't use touchegg so it's probably not related.

I found a workaround. When you login, you turn the extension off and on again, then screen locks in that session will not break swipe gesture (you have to do this every time you login). Alternatively, you can have the extension off by default and turn it on manually after login, then screen locks will not break swipe gesture. Basically, the problem only exists if Desktop-Cube is started at the same time as gnome-shell.

I hope this helps.

**Comment by Neo-29** [comment] 2024-05-25 20:43
> I have the same problem, and I don't use touchegg so it's probably not related.
> 
> I found a workaround. After you login, turn the extension off and on again, then screen locks in that session will not break swipe gesture (you have to do this every time you login). Alternatively, you can have the extension off by default and turn it on manually after login, then screen locks will not break swipe gesture. Basically, the problem only exists if Desktop-Cube is started at the same time as gnome-shell.
> 
> I hope this helps.

I think it's even more complicated than that.
I had to remove some extensions to get the gestures to work correctly.
It can happen with many extensions on.
I can't make a list but there are lots.

**Comment by Schneegans** [comment] 2024-05-26 11:54
Since I installed Ubuntu 24.04 I can confirm this. It's very hard to track down, though. I think I have a list of three extensions which is a pretty reliable reproducer:
* Desktop Cube
* Just Perfection
* Blur My Shell
If all of them are enabled, the gestures stop working. If either of the three is disabled, I cannot reproduce the issue. I have no idea about the reasons though...

**Comment by Neo-29** [comment] 2024-05-26 12:08
> Since I installed Ubuntu 24.04 I can confirm this. It's very hard to track down, though. I think I have a list of three extensions which is a pretty reliable reproducer:
> 
> * Desktop Cube
> * Just Perfection
> * Blur My Shell
> 
> If all of them are enabled, the gestures stop working. If either of the three is disabled, I cannot reproduce the issue. I have no idea about the reasons though...

Even with  built-in swipe gesture by gnome the pb occurs.

**Comment by Neo-29** [comment] 2024-05-26 12:14
> Can you guys reproduce this without Blur My Shell? Is there any other combination of extensions which causes this?

It can work with blur my shell.
I'm speaking of natural behavior (not with your extension) 
Desktop cube is a pb 
Just perfection is ok 

It can be something to track 

I'm not sure your extension is the culprick
It's a parameter, a setting somewhere in the extensions added to either mutter or gnome - shell 
causing this.

**Comment by FelixFourcolor** [comment] 2024-05-26 12:22
> Can you guys reproduce this without Blur My Shell?
It seems to me BMS must be enabled to reproduce the issue.
I don't find Just Perfection a factor. I can reproduce the issue when it's either enabled or disabled.

**Comment by Neo-29** [comment] 2024-05-26 12:23
> > Can you guys reproduce this without Blur My Shell?
> 
> It seems to me BMS must be enabled to reproduce the issue. I don't find Just Perfection a factor. I can reproduce the issue when it's either enabled or disabled.

It's a combination of extensions.
That's why it's hard to track.

**Comment by FelixFourcolor** [comment] 2024-05-26 12:27
> > I have the same problem, and I don't use touchegg so it's probably not related.
> > I found a workaround. After you login, turn the extension off and on again, then screen locks in that session will not break swipe gesture (you have to do this every time you login). Alternatively, you can have the extension off by default and turn it on manually after login, then screen locks will not break swipe gesture. Basically, the problem only exists if Desktop-Cube is started at the same time as gnome-shell.
> > I hope this helps.
> 
> I think it's even more complicated than that. I had to remove some extensions to get the gestures to work correctly. It can happen with many extensions on. I can't make a list but there are lots.

I can reliably make sure gestures don't break by doing that. I have Blur My Shell, Just Perfection, and 20 others extensions running.

**Comment by Neo-29** [comment] 2024-05-26 12:30
> > > I have the same problem, and I don't use touchegg so it's probably not related.
> > > I found a workaround. After you login, turn the extension off and on again, then screen locks in that session will not break swipe gesture (you have to do this every time you login). Alternatively, you can have the extension off by default and turn it on manually after login, then screen locks will not break swipe gesture. Basically, the problem only exists if Desktop-Cube is started at the same time as gnome-shell.
> > > I hope this helps.
> > 
> > 
> > I think it's even more complicated than that. I had to remove some extensions to get the gestures to work correctly. It can happen with many extensions on. I can't make a list but there are lots.
> 
> I can reliably make sure gestures don't break by doing that. I have Blur My Shell, Just Perfection, and 20 other extensions running.

Not a convenient solution.

**Comment by FelixFourcolor** [comment] 2024-05-26 12:32
Just saying it works. I haven't looked into it but there could be some ways to automate that.

**Comment by FelixFourcolor** [comment] 2024-05-26 12:37
Also I hope that provides some clues to help track it down. It probably has something to do with how gnome-shell initializes the extension at startup.

**Comment by Schneegans** [comment] 2024-05-26 13:24
> I don't find Just Perfection a factor. I can reproduce the issue when it's either enabled or disabled.

The weird thing is that if I have only Desktop Cube + Blur My Shell enabled, everything seems to work. I need at least a third extension to make it break.

Anyways, I just discovered that if I disallow Blur My Shell to be enabled at the login screen, the issue vanishes. To do so, you have to remove [this line](https://github.com/aunetx/blur-my-shell/blob/master/metadata.json#L12) in `~/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/metadata.json`. Does this also resolve the issue on your end?

**Comment by FelixFourcolor** [comment] 2024-05-26 20:19
> if I disallow Blur My Shell to be enabled at the login screen, the issue vanishes. To do so, you have to remove this line in ~/.local/share/gnome-shell/extensions/blur-my-shell@aunetx/metadata.json. Does this also resolve the issue on your end?

same for me

**Comment by FelixFourcolor** [comment] 2024-05-27 04:14
> > I don't find Just Perfection a factor. I can reproduce the issue when it's either enabled or disabled.
> 
> The weird thing is that if I have only Desktop Cube + Blur My Shell enabled, everything seems to work. I need at least a third extension to make it break.

Actually, I did not test with *only* DC + BMS. I can reproduce the issue when Just Perfection is either enabled or disabled, but in both cases all of my other extensions (about 20) are still running, any of them could be the third one to make it break.

**Comment by Schneegans** [comment] 2024-05-27 06:33
The problem seems to be that the order in which DC and BMS are loaded / unloaded is messed up in the problematic case. Usually, extensions should be unloaded exactly in reverse. This is very important when patching methods of GNOME Shell.

Consider two extensions patching the same method in GNOME Shell (as it's the case with DC and BMS, both mess with the `_prepareWorkspaceSwitch` of the  `WorkspaceAnimationController` - DC patches it [here](https://github.com/Schneegans/Desktop-Cube/blob/main/extension.js#L354) and BMS patches it [here](https://github.com/aunetx/blur-my-shell/blob/master/src/components/overview.js#L65)). If the extensions are loaded and unloaded correctly:
1. Extension A is loaded. It stores a backup of the original method of GNOME Shell and then replaces the method with its own variant.
2. Extension B is loaded. It also stores a backup, but as Extension A was loaded before, this will not be the vanilla version of GNOME Shell but already the one patched by Extension A.
3. Extension B is unloaded. It replaces the method of GNOME Shell with its stored backup (which is the version which includes the patches of Extension A).
4. Extension A is unloaded. It also replaces the method of GNOME Shell with its stored backup. This is the vanilla method, so everything is back to normal.

However, if the unloading order is reversed:
1. Extension A is loaded. Same as above.
2. Extension B is loaded. Same as above.
3. Extension A is unloaded. This replaces the method of GNOME Shell with its stored backup - The vanilla method! Even if Extension B is still loaded, its functionality is lost.
4. Extension B is unloaded. It replaces the method of GNOME Shell with its stored backup - the one with patches by Extension A! So we are now in a corrupt state - when GNOME Shell calls the method, code will be executed which belongs to an Extension which is not loaded.

As you can see, this is very important. Now I did some tests, and it looks like this:

|               | Blur My Shell _without_ `"unlock-dialog"`     | Blur My Shell _with_ `"unlock-dialog"` + No other extensions | Blur My Shell _with_ `"unlock-dialog"` + Any (?) other extension |
| ------------- | --------------------------------------------- | ------------------------------------------------------------ | ---------------------------------------------------------------- |
| Login         | Load Desktop Cube <br> Load Blur My Shell     | Load Blur My Shell <br> Load Desktop Cube                    | Load Blur My Shell <br> Load Desktop Cube                        |
| Lock Screen   | Unload Blur My Shell <br> Unload Desktop Cube | Unload Desktop Cube <br> Unload Blur My Shell                | Unload Blur My Shell <br> Unload Desktop Cube                    |
| Unlock Screen | Load Desktop Cube <br> Load Blur My Shell     | Load Blur My Shell <br> Load Desktop Cube                    | Load Blur My Shell <br> Load Desktop Cube                        |

The last column is the problematic one. When locking the screen with any (?) other extension enabled, Blur My Shell is unloaded before the Desktop Cube.

Why? I have no idea. I'll try to reach out to @aunetx and see if he has any idea.

**Comment by Schneegans** [comment] 2024-05-27 08:07
I asked about this on Matrix and was made aware of [this issue](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/7629). It seems that the only viable solution / workaround could be implemented on the Blur My Shell side...

**Comment by flexagoon** [comment] 2024-05-27 08:34
I already made a fix on the Blur My Shell side and it got merged

https://github.com/aunetx/blur-my-shell/pull/588

We just have to wait for the next release of BMS

**Comment by Schneegans** [comment] 2024-05-27 08:42
> I already made a fix on the Blur My Shell side and it got merged

Awesome! Then I think we can finally close this issue.

**Closed by Schneegans** 2024-05-27 08:42 UTC
Labels: bug

**Comment by Neo-29** [comment] 2024-05-27 09:27
I would keep it open.
Not sure of this as unique cause of the issue.
Someone tested it?

**Comment by Schneegans** [comment] 2024-05-27 10:18
For now, it is the only combination I am aware of. If you can reproduce the issue _without_ Blur My Shell, please list the extensions here.

**Comment by aunetx** [comment] 2024-05-27 12:22
Hello everyone, I am sorry for not posting the fix onto extensions.gnome.org before, I got pretty busy with exams for the past month... I will put it right now, and please keep me updated if anything else is needed!

**Comment by aunetx** [comment] 2024-05-27 12:24
Pushed the fix to version 62 :)

**Comment by Schneegans** [comment] 2024-05-27 17:58
Awesome! Thank you so much for your work!

**Comment by aunetx** [comment] 2024-05-28 08:20
Well, that was not my work but @flexagoon 's! But thank you still :D

**Comment by Neo-29** [comment] 2024-05-29 12:17
> Pushed the fix to version 62 :)

Tks a lot
This fixed ALL the issues with other extensions.

Swioe Gestures are now OK 👍👍👍
