### ISSUE TITLE
gnome-session crashes when logging and desktop-cube is enabled 

### ISSUE THREAD

**Issue by apisnu** [Schneegans/Desktop-Cube#94] opened 2022-10-17 00:18 UTC
## Describe the Bug
When I have _desktop cube_ enabled gnome freeze while logging in, and syslog is filled (gigabytes) with errors until it crashes. If I disable _desktop cube_ I have no problems. If I enable _desktop cube_ again while logged in everything works perfectly, the crash only happens when logging in to a new gnome-session. I also have _burn my windows_ which works perfectly.

Install _desktop cube_
Reboot
Log in to gnome

Syslog excerpt:
```
Oct 16 22:14:00 wukong gnome-shell[4309]: == Stack trace for context 0x563ae94ae4b0 ==
Oct 16 22:14:00 wukong gnome-shell[4309]: Attempting to run a JS callback during garbage collection. This is most likely caused by destroying a Clutter actor or GTK widget with ::destroy signal connected, or using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked.
Oct 16 22:14:00 wukong gnome-shell[4309]: == Stack trace for context 0x563ae94ae4b0 ==
Oct 16 22:14:00 wukong gnome-shell[4309]: == Stack trace for context 0x563ae94ae4b0 ==
Oct 16 22:14:00 wukong gnome-shell[4309]: The offending callback was SourceFunc().
Oct 16 22:14:00 wukong gnome-shell[4309]: == Stack trace for context 0x563ae94ae4b0 ==
Oct 16 22:14:00 wukong gnome-shell[4309]: == Stack trace for context 0x563ae94ae4b0 ==
Oct 16 22:14:00 wukong gnome-shell[4309]: Attempting to run a JS callback during garbage collection. This is most likely caused by destroying a Clutter actor or GTK widget with ::destroy signal connected, or using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked.
Oct 16 22:14:00 wukong gnome-shell[4309]: The offending callback was SourceFunc().
Oct 16 22:14:00 wukong gnome-shell[4309]: == Stack trace for context 0x563ae94ae4b0 ==
Oct 16 22:14:00 wukong gnome-shell[4309]: == Stack trace for context 0x563ae94ae4b0 ==
Oct 16 22:14:00 wukong gnome-shell[4309]: Attempting to run a JS callback during garbage collection. This is most likely caused by destroying a Clutter actor or GTK widget with ::destroy signal connected, or using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked.
Oct 16 22:14:00 wukong gnome-shell[4309]: == Stack trace for context 0x563ae94ae4b0 ==
Oct 16 22:14:00 wukong gnome-shell[4309]: == Stack trace for context 0x563ae94ae4b0 ==
Oct 16 22:14:00 wukong gnome-shell[4309]: The offending callback was SourceFunc().
Oct 16 22:14:00 wukong gnome-shell[4309]: Attempting to run a JS callback during garbage collection. This is most likely caused by destroying a Clutter actor or GTK widget with ::destroy signal connected, or using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked.
Oct 16 22:14:00 wukong gnome-shell[4309]: The offending callback was SourceFunc().
Oct 16 22:14:00 wukong gnome-shell[4309]: Attempting to run a JS callback during garbage collection. This is most likely caused by destroying a Clutter actor or GTK widget with ::destroy signal connected, or using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked.
Oct 16 22:14:00 wukong gnome-shell[4309]: The offending callback was SourceFunc().
Oct 16 22:14:00 wukong gnome-shell[4309]: Attempting to run a JS callback during garbage collection. This is most likely caused by destroying a Clutter actor or GTK widget with ::destroy signal connected, or using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked.
Oct 16 22:14:00 wukong gnome-shell[4309]: The offending callback was SourceFunc().
```

## System
 - Ubuntu 22.04.1 LTS
 - Desktop Cube version: 13
 - GNOME Shell 42.4

**Comment by Schneegans** [comment] 2022-10-17 07:03
Hi there! Thanks for the report! This should definitely not happen 😄 

Here are some things which could be of interest:
* Did the extension work on your system before or is it the first time you try to use it? 
* Have you tried disabling all other extensions?
* Have you tried this with both, Wayland and X11?

**Comment by Schneegans** [comment] 2022-12-30 12:34
Do you have any more input on this one? If not, I'll close this as I cannot reproduce it on my end.

**Closed** 2023-02-26 18:49 UTC
Labels: bug
