### ISSUE TITLE
Can't install desktop-cube

### ISSUE THREAD

**Issue by SpamixOfficial** [Schneegans/Desktop-Cube#112] opened 2023-02-07 09:02 UTC
Hello!

I've tried to install the extension both from Gnome Extensions and the zip file, but I always get this error:

The settings of extension desktop-cube@schneegans.github.com had an error:
```
Gtk.BuilderError: .:53:33 Invalid property: GtkMenuButton.icon-name
```

Stack trace:
```
PreferencesDialog@/home/alexander/.local/share/gnome-shell/extensions/desktop-cube@schneegans.github.com/prefs.js:50:19
buildPrefsWidget@/home/alexander/.local/share/gnome-shell/extensions/desktop-cube@schneegans.github.com/prefs.js:261:16
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:40
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:22
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:222:19
start@resource:///org/gnome/gjs/modules/script/package.js:206:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

Is there any solution?

**Comment by Schneegans** [comment] 2023-02-07 18:29
Thanks for the report, but this is a clear duplicate of the pinned issue #45.

**Closed by Schneegans** 2023-02-07 18:29 UTC
