### ISSUE TITLE
Cinnamon support?

### ISSUE THREAD

**Issue by asdf23** [Schneegans/Desktop-Cube#79] opened 2022-07-01 04:12 UTC
## The Motivation
I would like to  use this extension on Cinnamon

## The Solution
While using the cinnamon desktop I would like to see the 3d cube effect

## The Alternatives
There is a similar desktop cube that does a single animation trick.

**Comment by Schneegans** [comment] 2022-07-04 04:19
Thanks for the suggestion! However, this is a duplicate of #60.

**Closed by Schneegans** 2022-07-04 04:19 UTC
