### ISSUE TITLE
Plank Dock disappears after rotation

### ISSUE THREAD

**Issue by shadowboxdev** [Schneegans/Desktop-Cube#101] opened 2022-12-12 19:18 UTC
## Describe the Bug
__NOTE__: This only happens when dragging the cube from the desktop. Dragging a window from one side of the cube to another works as expected.

Rotating the cube causes the [Plank Dock](https://wiki.archlinux.org/title/Plank) not to render. After the issue occurs, if you drag a window to rotate the cube, the dock will come back (also closing and reopening plank). 

1. Install the [Plank Dock](https://wiki.archlinux.org/title/Plank) and have it running
2. Drag the cube from the desktop
3. Note that `Plank` no longer renders

## Expected Behavior
The Plank dock renders.

## System
_Please complete the following information:_
 - Linux distribution: __Ubuntu 22.10__
 - Desktop Cube version: __13__
 - GNOME Shell version: __43.0__

**Comment by Schneegans** [comment] 2022-12-13 08:40
Hi there & thanks for the report! I am using the same GNOME Shell & Ubuntu version and for me, this does not happen (the mouse pointer was not captured, but you get the point):

[Screencast from 2022-12-13 09-35-29.webm](https://user-images.githubusercontent.com/829942/207266827-3a96875b-cddd-4447-9516-78f9012dd48a.webm)

Have you tried running plank from a terminal and check its output? Maybe some error gets printed?

(And just out of curiosity: Why does one may want to run plank on top of GNOME?)

**Comment by Schneegans** [comment] 2022-12-30 12:34
Do you have any more input on this one? If not, I'll close this as I cannot reproduce it on my end.

**Closed** 2023-02-26 18:49 UTC
Labels: bug
