### ISSUE TITLE
KDE KWin Support

### ISSUE THREAD

**Issue by pnedyalkov91** [Schneegans/Desktop-Cube#134] opened 2023-09-11 11:04 UTC
I am a KDE user and love the extension. If you have free time to do that, could you port Desktop Cube for Kwin?
Many KDE users will be happy :) 
Thanks in advance!

**Comment by Schneegans** [comment] 2023-10-07 10:57
Thanks for the suggestion, but this is a duplicate of #83.

**Closed by Schneegans** 2023-10-07 10:57 UTC
